/**
 * Created by Alex on 22/05/2016.
 */

export default "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAICAIAAABLbSncAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3wIZFDQQxd+nEAAAAB1pVFh0Q29tbWVudAAAAAAAQ3JlYXRlZCB3aXRoIEdJTVBkLmUHAAAAH0lEQVQI12NkQAL///+Hs5kYcADSJRiRzWVkZKSFHQBYfwYMUOT4KAAAAABJRU5ErkJggg==";
